#!/bin/bash

if [[ $EUID -ne 0 ]]; then
        echo "This Script must be run as root"
        exit 1

else

        echo "updating and upgrade"
        apt-get update
        sudo apt-get upgrade -y

        sudo apt-get install dialog
        cmd=(dialog --separate-output --checklist "Please Select Software you want to install:" 22 76 16)
        options=( 1 "Apache 2" off
                  2 "Mysql Server" off
                  3 " Java 8 " off
                  4 " Apache Tomcat" off )

        choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
        clear
        for choice in $choices
        do
                case $choice in

                        1)
                                 echo " Installing Apache"
                                 apt install apache2 -y
                                 echo " Restarting Apache"
                                 service apache2 restart
                                 hostname -I | awk '{print $1}'
                                 ;;

                        2)

                                 echo " Installing mysql Server"
                                 apt install mysql-server -y
                                 ;;

                        3)
                                 echo "Installing JDK 8"
                                 sudo apt install openjdk-8-jre-headless -y
                                 ;;

                        4)
                                 echo " Installing Apache Tomact"
                                 mkdir /opt/tomcat
                                 cd /opt/tomcat
                                 wget https://apache.claz.org/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
                                 tar xvzf apache-tomcat-8.5.54.tar.gz
                                 ;;
                        esac
                done

fi

