#!/bin/bash

if [[ $EUID -ne 0 ]]; then
        echo "This Script must be run as root"
        exit 1

else 
        echo "updating and upgrade"
        apt-get update
        sudo apt-get upgrade -y

        echo " Installing Apache"
        apt install apache2 -y
        echo " Restarting Apache"
        service apache2 restart
        hostname -I | awk '{print $1}'

        echo " Installing mysql Server"
        apt install mysql-server -y

        echo "Installing JDK 8"
        sudo apt install openjdk-8-jre-headless -y

        echo " Installing Apache Tomact"
        mkdir /opt/tomcat
        cd /opt/tomcat
        wget https://apache.claz.org/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
        tar xvzf apache-tomcat-8.5.54.tar.gz

fi









